database:
    name: squid_auth
    user: root
    pass: root

server:
    port: 9999
    interface: localhost

auth_callback:
    # Console command executed after new user auth.
    # Possible placeholders for auth callbacks: username, id,  time, ip
    success: echo 'User {login} with id {id} authorized at {time} from {ip}'
    fail: stuff
