database:
    host: localhost
    name: squid_auth
    user: root
    pass: root

validator:
    port: 9999
    interface: localhost
    login_timeout: 30 # in seconds
    database_update_timeout: 600
    # Console command executed after new user auth.
    # Possible placeholders for auth callbacks:
    #   ip, user_id, dept_id, login, passwd, admin_level, login_time
    callback:
        success: echo 'User {login} with id {user_id} authorized at {login_time} from {ip}'
        fail: stuff

ip_checker:
    port: 9998
    interface: localhost

ip_info:
    port: 9997
    interface: localhost