database:
    host: localhost
    name: squid_auth
    user: root
    pass: root

validator:
    port: 9999
    interface: localhost
    login_timeout: 30 # in seconds
    # Console command executed after new user auth.
    # Possible placeholders for auth callbacks:
    #   ip, user_id, dept_id, login, passwd, admin_level, login_time
    success_callback: echo 'User {login} with id {user_id} authorized at {login_time} from {ip}'
    fail_callback: stuff

ip_checker:
    port: 9998
    interface: localhost
